### ISSUE TITLE
rnn train always stop

### ISSUE THREAD

**Issue by zhouhuirun2015** [jagger2048/rnnoise-windows#11]
clean audio is silent audio, noise audio is pink noise audio, 175MB/48000hz/1channel/S16le

while exec python rnn_train.py feature.h5, it always stop here
![image](https://user-images.githubusercontent.com/15274287/83998878-250bb680-a994-11ea-9a34-4de43e7d6e2f.png)

**Comment by jagger2048** [comment]
Hi,
  It seems like it was caused by the out-of-memory issue, CPU ram. Reduce
the batch size might solve the problem.  You can reference the link
<https://ai-experiments.com/model-training-in-keras-and-python/> .

B&R
Jagger

**Comment by zhouhuirun2015** [comment]
Thanks for your reply.
It did not work when i change batch size from 128 to 32.
It did work to use a 16GB memory pc to train.
