### ISSUE TITLE
How to train this with larger dataset (More than just a pair of noise data and clean speech)

### ISSUE THREAD

**Issue by Bach1502** [jagger2048/rnnoise-windows#16]
Hello,
I believe that this is a fairly simple question but since I'm very new to ML in general, it still baffles me. I just followed the training instruction and has successfully trained my model on one pair of data (a clean speech.wav and a noise.wav) now I want to ask how can you repeat this process for larger dataset, I'm currently having a set of data with 300 files for these 2 categories and I don't think repeating this process 300 times is the way I should go.

Thanks.

**Comment by jagger2048** [comment]
Hi Bach1502,
  As far as I know, you can cascade these 300 files into one file for a
large dataset instead of repeating 300 times in this case. Finally, you
will get two wave files which contain two categories 300 files.

Best Regards,
Jagger

**Comment by Bach1502** [comment]
Hi Jagger,
I'm sorry for not fully understanding what you mean for cascading. Right now, I'm having 600 wav files in total (sorry for the confusion, what I meant in the original post was that these 600 files were equally divided into 300 wav files of two categories), by that did you mean that I can combine these 600 files into 2 wav files (one for the clean speech and one for the noisy)? Also, I'm not sure what I should do to combine this, as the approach I'm thinking of right now is opening something like Audacity and manually combine them there. 

Thank you for responding, 

Bach

**Comment by jagger2048** [comment]
Hi Bach1502,
  1. The answer is yes. You should combine 300 clean wave files into one wavfile, 300 noise wave files into another wavfile. These two Wav files can be used for training.
  2.  You can reference the python script I provided to combine the Wav files in a direction, which recursively search for all wav files in the current directory and call sox to combine all wav files.

 Usage:

```
  cd <direction_clean_wav_files>
  python search_wav_and_combine.py
```
example:
❯ python search_wav_and_combine.py
/mnt/c/workspace/audio_data/amazon-auto/noise_mixer/tx-noise/Conference1_handsfree.wav
/mnt/c/workspace/audio_data/amazon-auto/noise_mixer/tx-noise/Conference2_handsfree.wav
/mnt/c/workspace/audio_data/amazon-auto/noise_mixer/tx-noise/Conference3_handsfree.wav
use sox to combine the wavfile ...
3
Input formats were only specified for 0 out of 3 files.The last 3 files will remain unformatted.
finish...

  [search_wav_and_combine.zip](https://github.com/jagger2048/rnnoise-windows/files/7364486/search_wav_and_combine.zip)

Best regards,
Jagger

**Comment by Bach1502** [comment]
Thank you ! I have managed to concatenate these files into the necessary training files with your script.
