### ISSUE TITLE
Using a resampler for 16KHz

### ISSUE THREAD

**Issue by carlfm01** [jagger2048/rnnoise-windows#7]
Hello @jagger2048, thanks for your Windows adaption, I have successfully trained my own model and it is working really well with your adaption using 48KHz.

Now I need to add RNNoise to the Mozilla's DeepSpeech feeding pipeline, first I'm experimenting with your adaption and https://github.com/cpuimage/resampler to up-sample/down-sample. It is working but it generates a weird sound like static:
[cleanspeech.zip](https://github.com/jagger2048/rnnoise-windows/files/3948296/cleanspeech.zip)

The code that I'm using with the resampler mentioned above :

https://gist.github.com/carlfm01/c8f49562b97a66fea1a72d23d1259b7d

Any idea of what's wrong? 

Thanks.

**Comment by jagger2048** [comment]
Hi,
  Your process flow is OK. But the result sounds not so good from your test audio data. You can first check whether the output of the RNNoise with 48k audio is as expected or not. If so, the main issue should be the resampler processing. I will help to check that issue.

**Comment by carlfm01** [comment]
> You can first check whether the output of the RNNoise with 48k audio is as expected or not

Yes, it works leaving the audio with clean speech untouched and with noisy speech it works as expected removing the noise when using the 48k data.





> If so, the main issue should be the resampler processing.

It was my thought at first, but then testing only downsampling and upsampling without feeding RNNoise works properly without adding any noise.

If I feed 16k data and don't downsample back to 16k the noise is still there, let me test feeding 48k and downsampling.



>  I will help to check that issue.

It would be amazing, I don't hold expertise with C/C++ so that help will be a lot.

**Comment by carlfm01** [comment]
Feeding 48k data directly to RNNoise and downsampling to 16k works fine without adding weird noise to the result.

**Comment by jagger2048** [comment]
> Feeding 48k data directly to RNNoise and downsampling to 16k works fine without adding weird noise to the result.

Hi, sorry for replying so late. I checked the rnnoise model and it worked well for original 48k audio data and 48k audio data upsample from 16k by Auditon. The main issue is the resampler you applied. In fact, I had written some test codes to test the resampler and it worked.a. a bit bad in my opinion =-=. I cannot believe that resample from 16k to 16k with this resampler will produce the weird noise. So I did a further test and found some issues of the resample.

For example, feed a 1k sine signal with sample rate 16k. Then upsample to 48k with the resampler. You will find some high-frequency image signals in the frequency domain. It needs an anti-image filter to remove these signal in general. I can NOT find this processing in the resample. For the downsampling case, it also requires anti-aliasing filtering but the resample has not that one.

**Resample input(1k sine signal, 16k)**
![](https://myblog-repo.oss-cn-shenzhen.aliyuncs.com/blog/20191212225422.png)

**Resample output(1k sine signal, 48k)**
![](https://myblog-repo.oss-cn-shenzhen.aliyuncs.com/blog/20191212225525.png)

![](https://myblog-repo.oss-cn-shenzhen.aliyuncs.com/blog/20191212225541.png)

You can try another resampler instead to avoid the weird noise and meet your needs. I will add a new resampler for this project to support the multiple sample rate situation in next versions.

**Comment by carlfm01** [comment]
> Hi, sorry for replying so late.

No problem, actually it was quick.



> You can try another resampler instead to avoid the weird noise and meet your needs.

Testing this one : https://github.com/cpuimage/resampler/blob/dcf9291b8abe1d476c58b2cb794e34c41f9bf285/main.c#L85

The weird noise is gone, now I'm testing how it impacts the WER on clean speech.


> I will add a new resampler for this project to support the multiple sample rate situation in next versions.

Will keep an eye on, thanks.

Will share the WER results just FTR and then close the issue.

**Comment by carlfm01** [comment]
**Libri test-clean**
WER: 0.074540
WER: 0.075113  With RNNoise

**Libri test-other**
WER: 0.224832
WER: 0.231262 With RNNoise

Minimal impact on clean speech, we can close now.

@jagger2048 Thanks for your support.
