### ISSUE TITLE
dll-version

### ISSUE THREAD

**Issue by CobraCalle** [jagger2048/rnnoise-windows#9]
Hello,

I`m using the original rnnoise at a probject that runs on Linux- and WIndows-machines. So I would like zo build rnnoise for windows as a dll that has the exact same entrypoints as the original version... to be able to use the dotnet part unchanged on Linux and Windows.

Sadly, my c++-skills aren´t the best... can anyone help me?

Thanks alot.

Carl

**Comment by jagger2048** [comment]
Hi Carl,
  Glad this project can help you. For the DLL version, I will test and
release to you this week. The interface would be the same as `
rnnoise-windows/include/rnnoise.h`, which is the original one and only
support 48 k signal input.

Best regard,
Jagger

**Comment by CobraCalle** [comment]
Hi Jagger,

I've just managed to build a dll-version... but updating your repository, so that it is useable for both (like the original version -> demo-cmd-tool that uses the lib) would be perfect and would allow to use your code unchanged (the changes I made are very rough I think :-) )

Do you know how rnnoise is trained in you repo? I think there are two differend versions to train in the orginal version, that suppress different type of background noise... or did I get that wrong?

thanks a lot 

carl

**Comment by jagger2048** [comment]
Hi Carl,
 I know your requirement. The current project is in hard code, the
command-like tool may be more  convenient for the user. I will pay
attention to these.

For the training step, I have updated in the README,e.g. how to train your
model, you can reference it to train your own model. As far as I know, the
training method is the same as the original one in this repo. I just update
some parameter for easy using.

Best Regards,
Jagger

**Comment by CobraCalle** [comment]
Thank you very much... I'll try to train my own model with original recordings from the hardware I use.

Best Regards,
Carl

**Comment by jagger2048** [comment]
Hi Carl,
  I have updated a DLL export project in the VS solution, `dev branch`. Please note that there may be some issues as it has not been fully tested.
B&R,
Jagger
